# Generated by Django 4.2.10 on 2024-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRadar', '0004_book_average_rating_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('SCIFI', 'Science Fiction'), ('FANTASY', 'Fantasy'), ('MYSTERY', 'Mystery'), ('HORROR', 'Horror'), ('COMEDY', 'Comedy'), ('HISTORICAL', 'Historical Fiction'), ('NON_FICTION', 'Non-Fiction')], max_length=20, null=True),
        ),
    ]
