# Generated by Django 4.2.10 on 2024-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRadar', '0005_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(1, 'Romance'), (2, 'Thriller'), (3, 'Science Fiction'), (4, 'Fantasy'), (5, 'Mystery'), (6, 'Horror'), (7, 'Comedy'), (8, 'Historical Fiction'), (9, 'Non-Fiction')], null=True),
        ),
    ]
