# Generated by Django 4.2.10 on 2024-06-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookRadar', '0006_alter_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ranking',
        ),
    ]
